### ISSUE TITLE
Error occured on determining the exact loader.

### ISSUE THREAD

**Issue by sowbener** [wwh1004/ConfuserExTools#1]
"Tool.Loader.Auto.exe ConfuserExKiller.dll -f your_assembly_path"

using this command line

The following error i have:
Error occured on determining the exact loader.
Using loader: Tool.Loader.CLR40.x86.exe

Onverwerkte uitzondering: System.IO.FileNotFoundException: The system cannot find the specified file
(Uitzondering van HRESULT: 0x80070002)
   bij System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   bij System.Reflection.Assembly.LoadFile(String path)
   bij Tool.Loader.Loader.Execute(String[] args)
   bij Tool.Loader.CLR40.x86.Program.Main(String[] args)

CMD is run as administrator.

**Comment by wwh1004** [comment]
you should decompress all files into the directory

**Comment by sowbener** [comment]
The zip archive is extracted to a directory

**Comment by wwh1004** [comment]
It works properly for me. You should debug it with dnSpy.

**Comment by sowbener** [comment]
I will debug it soon, have had no time yet. please keep the issue open

**Comment by sowbener** [comment]
nvm lol i just missed a .dll in the directory sorry for wasting your time.
